# Generated by Django 5.1.1 on 2025-01-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso_neto',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
