# Generated by Django 5.1.1 on 2025-01-13 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_producto_peso_neto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='peso_neto',
            field=models.IntegerField(),
        ),
    ]
