# Generated by Django 5.1.1 on 2025-01-16 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0004_usersession'),
    ]

    operations = [
        migrations.AddField(
            model_name='proveedor',
            name='cantidad_por_bulto',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='descripcion',
            field=models.CharField(default='proveedor', max_length=50),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='imagen_proveedor',
            field=models.ImageField(blank=True, null=True, upload_to='proveedores/'),
        ),
        migrations.AddField(
            model_name='proveedor',
            name='precio_bulto',
            field=models.DecimalField(decimal_places=2, default=4000, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='proveedor',
            name='producto_bulto_cerrado',
            field=models.CharField(default='producto propio proveedor', max_length=50),
        ),
    ]
