# Generated by Django 5.1.1 on 2025-01-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0005_proveedor_cantidad_por_bulto_proveedor_descripcion_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proveedor',
            name='cantidad_por_bulto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='precio_bulto',
        ),
        migrations.RemoveField(
            model_name='proveedor',
            name='producto_bulto_cerrado',
        ),
        migrations.AlterField(
            model_name='proveedor',
            name='imagen_proveedor',
            field=models.ImageField(blank=True, null=True, upload_to='img/proveedores/'),
        ),
    ]
