# Generated by Django 5.1.1 on 2025-01-17 12:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0006_remove_proveedor_cantidad_por_bulto_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductoProveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=50)),
                ('fecha_vencimiento', models.DateField()),
                ('codigo_bulto', models.IntegerField()),
                ('cantidad_bulto', models.IntegerField()),
                ('precio_bulto', models.DecimalField(decimal_places=2, max_digits=10)),
                ('marca', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.marca')),
                ('proveedor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.proveedor')),
            ],
        ),
    ]
