# Generated by Django 5.1.1 on 2025-01-17 12:10

import app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0007_productoproveedor'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productoproveedor',
            name='codigo_bulto',
            field=models.IntegerField(default=app.models.generar_codigo_aleatorio),
        ),
    ]
