# Generated by Django 5.1.1 on 2025-01-22 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0010_carritoitem_total_a_pagar'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritoitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10),
            preserve_default=False,
        ),
    ]
