# Generated by Django 5.1.1 on 2025-01-22 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_carritoitem_sub_total'),
    ]

    operations = [
        migrations.AlterField(
            model_name='carritoitem',
            name='sub_total',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AlterField(
            model_name='carritoitem',
            name='total_a_pagar',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
