# Generated by Django 5.1.1 on 2025-01-23 11:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_carritoitem_sub_total_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarritoHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('sub_total', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total_a_pagar', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('procesado', models.BooleanField(default=False)),
                ('eliminado', models.BooleanField(default=False)),
                ('fecha_procesado', models.DateTimeField(auto_now_add=True)),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.productoproveedor')),
            ],
        ),
    ]
