# Generated by Django 5.1.1 on 2025-01-23 14:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_transacciones_carritohistorial_transaccion'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transacciones',
            name='proveedor',
        ),
    ]
