# Generated by Django 5.1.1 on 2025-01-24 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0015_remove_transacciones_proveedor'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritohistorial',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
        migrations.AddField(
            model_name='carritoitem',
            name='proveedor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='app.proveedor'),
        ),
    ]
