# Generated by Django 5.1.1 on 2025-01-30 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_proveedor_activo'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritohistorial',
            name='fecha_de_entrega',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
