# Generated by Django 5.1.1 on 2025-01-30 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0018_carritohistorial_fecha_de_entrega'),
    ]

    operations = [
        migrations.AddField(
            model_name='carritohistorial',
            name='estado',
            field=models.CharField(choices=[('pendiente', 'Pendiente'), ('entregado', 'Entregado')], default='pendiente', max_length=10),
        ),
    ]
